version: '3'
services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - /mnt/testAirflow/dags:/opt/airflow/dags
      - /mnt/testAirflow/logs:/opt/airflow/logs
    depends_on:
      - postgres
    command: ["bash", "-c", "/home/airflow/init_airflow.sh"]

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"  # 추가된 부분
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow

